remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Alex Surprenant's ePortfolio Page
description: A place where you can check out the projects that i have been working on in SNHU
